@startuml
skinparam backgroundColor white
skinparam defaultFontSize 24
skinparam shadowing false
skinparam actorStyle awesome

left to right direction

actor "Uživatel" as user

rectangle "Bitcoin Multisig Wallet" {
  usecase "UC1: Připojení\nTrezoru\na přihlášení" as UC1
  usecase "UC2: Odeslání\nsinglesig\ntransakce" as UC2
  usecase "UC3: Import\nmultisig\npeněženky" as UC3
  usecase "UC4: Vytvoření\na podepsání\nmultisig transakce" as UC4
  usecase "UC5: Manuální\nvýběr UTXO\n(coin control)" as UC5
  usecase "UC6: Stav PSBT\na doplnění\npodpisu" as UC6
}

user -- UC1
user -- UC2
user -- UC3
user -- UC4
user -- UC5
user -- UC6

UC2 ..> UC5 : <<extend>>
UC4 ..> UC6 : <<include>>

@enduml
