registry {
  host = "0.0.0.0"
  port = 8082
}

db {
  url = "jdbc:postgresql://localhost:5432/wallet_registry"
  user = "wallet"
  password = "wallet"

  url = ${?REGISTRY_DB_URL}
  user = ${?REGISTRY_DB_USER}
  password = ${?REGISTRY_DB_PASSWORD}
}
